// AUTH
export const AUTH_SUCCESSFULLY = 'AUTH_SUCCESSFULLY';
export const LOGOUT = 'LOGOUT';

// ADMIN
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';

// CUSTOMER
export const ORDER_PRODUCT = 'ORDER_PRODUCT';
