// AUTH
export const AUTH_SUCCESSFULLY = 'AUTH_SUCCESSFULLY';
export const LOGOUT = 'LOGOUT';


// ADMIN
export const INIT_PRODUCTS = 'INIT_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const GET_STATISTICS = 'GET_STATISTICS';



// CUSTOMER
export const INIT_PROFILE = 'INIT_PROFILE';
export const ADD_TO_CART_PRODUCT = 'ADD_TO_CART_PRODUCT';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ORDER = 'ORDER';

